<?php

namespace app\models;

use app\components\ImageBehavior;
use Yii;

/**
 * This is the model class for table "article".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $image
 */
class Article extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        return [
            'class' => ImageBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'article';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['title', 'description'], 'string', 'max' => 255],
            [['image'], 'file', 'extensions' => 'jpg,png'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'image' => 'Image',
        ];
    }

    public function saveImage($filename)
    {
        $this->image = $filename;

        return $this->save(false);
    }


    public function getImage()
    {
        return $this->image ? '/uploads/' . $this->image : 'no-image.jpg';
    }

    public function beforeDelete()
    {
        $this->deleteCurrentImage($this->image);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
